name: my-app
services:
  - name: nodejs-service
    github:
      repo: your-github-repo-url
      branch: main
    environment_slug: node-js
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000

  - name: python-service
    github:
      repo: your-github-repo-url
      branch: main
    environment_slug: python
    build_command: pip install -r requirements.txt
    run_command: python update_emergence_issue_of_the_month_data.py
    http_port: 5000
    
  - environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: digitalocean/sample-python
    name: sample-python

domains:
  - domain: www.yourdomain.com
    type: PRIMARY

scale:
  nodejs-service:
    min_instances: 1
    max_instances: 3
  python-service:
    min_instances: 1
    max_instances: 3
