# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR /EGYPT-HORIZON-SCANNER-BACKEND

# Install Python
RUN apt-get update && apt-get install -y python3

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Start the application
CMD [ "npm", "start" ]